version: "3.8"

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql-master
      - redis
    environment:
      - MYSQL_HOST=mysql-master
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=product_db

  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mysql-master:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: product_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-master-data:/var/lib/mysql
    command: --server-id=1 --log-bin=mysql-bin --gtid-mode=ON --enforce-gtid-consistency --binlog-format=row

  mysql-slave1:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql-slave1-data:/var/lib/mysql
    command: --server-id=2 --log-bin=mysql-bin --gtid-mode=ON --enforce-gtid-consistency --binlog-format=row --replicate-do-db=product_db
    depends_on:
      - mysql-master

  mysql-slave2:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql-slave2-data:/var/lib/mysql
    command: --server-id=3 --log-bin=mysql-bin --gtid-mode=ON --enforce-gtid-consistency --binlog-format=row --replicate-do-db=product_db
    depends_on:
      - mysql-master

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  mysql-master-data:
  mysql-slave1-data:
  mysql-slave2-data:
  redis-data:
